// Export the MODULE_CAPABILITIES from the document provided
export const MODULE_CAPABILITIES: Record<number, {
    name: string;
    relays: number | number[];
    sensors: string[];
    dimmer: boolean;
    shutter: boolean;
    other: string
}> ={
        0: { name: 'Template', relays: 0, sensors: [], dimmer: false, shutter: false, other: 'Custom template; assume user-configured' },
        1: { name: 'Sonoff Basic', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        2: { name: 'Sonoff RF', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        3: { name: 'Sonoff SV', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        4: { name: 'Sonoff TH', relays: 1, sensors: ['temperature', 'humidity'], dimmer: false, shutter: false, other: '' },
        5: { name: 'Sonoff Dual', relays: 2, sensors: [], dimmer: false, shutter: false, other: '' },
        6: { name: 'Sonoff POW', relays: 1, sensors: ['power'], dimmer: false, shutter: false, other: '' },
        7: { name: 'Sonoff 4Ch', relays: 4, sensors: [], dimmer: false, shutter: false, other: '' },
        8: { name: 'Sonoff S2X', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        9: { name: 'Slampher', relays: 1, sensors: [], dimmer: true, shutter: false, other: '' },
        10: { name: 'Sonoff Touch', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        11: { name: 'Sonoff LED', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        12: { name: '1 Channel', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        13: { name: '4 Channel', relays: 4, sensors: [], dimmer: false, shutter: false, other: '' },
        14: { name: 'Motor C/AC', relays: 1, sensors: [], dimmer: false, shutter: true, other: '' },
        15: { name: 'ElectroDragon', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        16: { name: 'EXS Relay(s)', relays: [2, 4], sensors: [], dimmer: false, shutter: false, other: '' },
        17: { name: 'WiOn', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        18: { name: 'Generic', relays: 0, sensors: [], dimmer: false, shutter: false, other: 'Custom GPIO; assume user-configured' },
        19: { name: 'Sonoff Dev', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        20: { name: 'H801', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        21: { name: 'Sonoff SC', relays: 0, sensors: ['motion'], dimmer: false, shutter: false, other: '' },
        22: { name: 'Sonoff BN-SZ', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        23: { name: 'Sonoff 4Ch Pro', relays: 4, sensors: [], dimmer: false, shutter: false, other: '' },
        24: { name: 'Huafan SS', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        25: { name: 'Sonoff Bridge', relays: 0, sensors: [], dimmer: false, shutter: false, other: '' },
        26: { name: 'Sonoff B1', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        27: { name: 'AiLight', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        28: { name: 'Sonoff T1 1Ch', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        29: { name: 'Sonoff T1 2Ch', relays: 2, sensors: [], dimmer: false, shutter: false, other: '' },
        30: { name: 'Sonoff T1 3Ch', relays: 3, sensors: [], dimmer: false, shutter: false, other: '' },
        31: { name: 'Supla Espablo', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        32: { name: 'Witty Cloud', relays: 1, sensors: ['light'], dimmer: false, shutter: false, other: '' },
        33: { name: 'Yunshan Relay', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        34: { name: 'MagicHome', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        35: { name: 'Luani HVIO', relays: 4, sensors: [], dimmer: false, shutter: false, other: '' },
        36: { name: 'KMC 70011', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        37: { name: 'Arilux LC01', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        38: { name: 'Arilux LC11', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        39: { name: 'Sonoff Dual R2', relays: 2, sensors: [], dimmer: false, shutter: false, other: '' },
        40: { name: 'Arilux LC06', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        41: { name: 'Sonoff S31', relays: 1, sensors: ['power'], dimmer: false, shutter: false, other: '' },
        42: { name: 'Zengge WF017', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        43: { name: 'Sonoff Pow R2', relays: 1, sensors: ['power'], dimmer: false, shutter: false, other: '' },
        44: { name: 'Sonoff iFan02', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        45: { name: 'BlitzWolf SHP', relays: 1, sensors: ['power'], dimmer: false, shutter: false, other: '' },
        46: { name: 'Shelly 1', relays: 1, sensors: ['power'], dimmer: false, shutter: false, other: '' },
        47: { name: 'Shelly 2', relays: 2, sensors: ['power'], dimmer: false, shutter: true, other: '' },
        48: { name: 'Xiaomi Philips', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        49: { name: 'Neo Coolcam', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        50: { name: 'ESP Switch', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        51: { name: 'OBI Socket', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        52: { name: 'Teckin', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        53: { name: 'APLIC WDP303075', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        54: { name: 'TuyaMCU', relays: [1,2,3,4], sensors: [], dimmer: false, shutter: false, other: '' },
        55: { name: 'Gosund SP1 v23', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        56: { name: 'Armtronix Dimmers', relays: 1, sensors: [], dimmer: true, shutter: false, other: '' },
        57: { name: 'SK03 Outdoor (Tuya)', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        58: { name: 'PS-16-DZ', relays: [1,2,3,4], sensors: [], dimmer: false, shutter: false, other: '' },
        59: { name: 'Teckin US', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        60: { name: 'Manzoku Strip (EU 4)', relays: [1,2,3,4], sensors: [], dimmer: false, shutter: false, other: '' },
        61: { name: 'OBI Socket 2', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        62: { name: 'YTF IR Bridge', relays: 0, sensors: [], dimmer: false, shutter: false, other: '' },
        63: { name: 'Digoo DG-SP202', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        64: { name: 'KA10', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        65: { name: 'Luminea ZX2820', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        66: { name: 'Mi Desk Lamp', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        67: { name: 'SP10', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        68: { name: 'WAGA CHCZ02MB', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        69: { name: 'SYF05', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        70: { name: 'Sonoff L1', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        71: { name: 'Sonoff iFan03', relays: 1, sensors: [], dimmer: false, shutter: false, other: '' },
        72: { name: 'EX-Store Dimmer', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        73: { name: 'PWM Dimmer', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        74: { name: 'Sonoff D1 Dimmer', relays: 0, sensors: [], dimmer: true, shutter: false, other: '' },
        75: { name: 'Sonoff ZbBridge', relays: 0, sensors: [], dimmer: false, shutter: false, other: '' },
        // Add more as new modules are released in Tasmota; unknown modules default to no support
      };